This is a testharness.js-based test.
[FAIL] Controllers can be GCed when their signals are being followed (using TaskSignal and TaskController)
  promise_test: Unhandled rejection with value: object "ReferenceError: gc is not defined"
[FAIL] Signals can be GCed when all abort sources have been GCed (using TaskSignal and TaskController)
  promise_test: Unhandled rejection with value: object "ReferenceError: gc is not defined"
[FAIL] Signals can be GCed when they have no references or event listeners (using TaskSignal and TaskController)
  promise_test: Unhandled rejection with value: object "ReferenceError: gc is not defined"
[FAIL] Signals can be GCed when they have no references or relevant event listeners (using TaskSignal and TaskController)
  promise_test: Unhandled rejection with value: object "ReferenceError: gc is not defined"
[FAIL] Signals can be GCed when all abort event listeners have been removed (using TaskSignal and TaskController)
  promise_test: Unhandled rejection with value: object "ReferenceError: gc is not defined"
[FAIL] Signals are not GCed before being aborted by a controller when they have abort event listeners (using TaskSignal and TaskController)
  promise_test: Unhandled rejection with value: object "ReferenceError: gc is not defined"
[FAIL] Composite signals are not GCed before being aborted by timeout when they have abort event listeners (using TaskSignal and TaskController)
  promise_test: Unhandled rejection with value: object "ReferenceError: gc is not defined"
[FAIL] Temporary composite signals used for constructing other composite signals can be GCed (using TaskSignal and TaskController)
  promise_test: Unhandled rejection with value: object "ReferenceError: gc is not defined"
[FAIL] Nested and intermediate composite signals can be GCed when expected (using TaskSignal and TaskController)
  promise_test: Unhandled rejection with value: object "ReferenceError: gc is not defined"
[FAIL] Settled composite signals with event listeners can be GCed (using TaskSignal and TaskController)
  promise_test: Unhandled rejection with value: object "ReferenceError: gc is not defined"
Harness: the test ran to completion.
