This is a testharness.js-based test.
[FAIL] Async gc() should not cause a leak
  promise_test: Unhandled rejection with value: object "ReferenceError: gc is not defined"
Harness: the test ran to completion.
