This is a testharness.js-based test.
[FAIL] attributionsrc request has the proper format.
  promise_test: Unhandled rejection with value: object "Error: Tried to run in a non-testharness window without a call to set_test_context"
Harness: the test ran to completion.
